// Central Lucide catalog: every icon in the product comes from here, so
// naming and sizing stay consistent. Additions are deliberate, not ad-hoc.
export {
  Bell,
  Building2,
  ChartColumn,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  ClipboardList,
  FileText,
  Inbox,
  LayoutDashboard,
  Menu,
  Pencil,
  Plus,
  Receipt,
  ScrollText,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  Tags,
  Trash2,
  TriangleAlert,
  Truck,
  User,
  Users,
  Wallet,
  X,
} from 'lucide-angular';
export type { LucideIconData } from 'lucide-angular';
